import type { Metadata } from "next";
import Navbar from "@/components/navBar/Navbar";
import Footer from "@/components/Footer";
import Branches from "@/components/Branches";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "City of God Covenant Church",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <Navbar />
      {children}
      <Branches />
      <Footer />
      <Toaster position="bottom-right" reverseOrder={false} />
    </main>
  );
}
